In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentences
sent =[ 'the glass of milk',
         'the glass of juice',
         'the cup of tea',
         'understand the meaning of words',
         'you have done your work very well', ]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'understand the meaning of words',
 'you have done your work very well']

In [4]:
## Defining the Vocabulary size
voc_size = 10000

In [5]:
## One Hot Representation
## These below are the indexes which tell that which word of the first sentence is represented by which index Each word has it's own index representation.
one_hot_repr = [one_hot (words , voc_size) for words in sent]
one_hot_repr

[[3005, 1010, 4843, 3022],
 [3005, 1010, 4843, 3446],
 [3005, 2913, 4843, 6644],
 [9923, 3005, 7707, 4843, 4024],
 [8639, 6051, 4655, 7779, 3094, 5266, 7923]]

In [6]:
## Word Embedding Representation
## pad_sequence is used to make the length of the one hot representations of the same length.
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [ ]:
## if using the pre option , then all the zeros will come in the first during the padding.
## and if the post option is used then all the zeros will come at the end of the representations.
sent_length = 10
embeded_docs = pad_sequences(one_hot_repr ,padding='pre',maxlen=sent_length)
print(embeded_docs)

[[   0    0    0    0    0    0 3005 1010 4843 3022]
 [   0    0    0    0    0    0 3005 1010 4843 3446]
 [   0    0    0    0    0    0 3005 2913 4843 6644]
 [   0    0    0    0    0 9923 3005 7707 4843 4024]
 [   0    0    0 8639 6051 4655 7779 3094 5266 7923]]


In [9]:
## feature representations
dim = 10


In [10]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Python learning\11-Deep Learning NLP\env\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step


array([[[ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.02524853,  0.01830753, -0.01433732, -0.0

In [13]:
embeded_docs[0]

array([   0,    0,    0,    0,    0,    0, 3005, 1010, 4843, 3022],
      dtype=int32)

In [14]:
model.predict(np.expand_dims(embeded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[[ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.04651535,  0.04601022,  0.04831455,  0.04909411,
         -0.02664808, -0.02505817,  0.01569512, -0.00075625,
         -0.04684513, -0.02374986],
        [ 0.02524853,  0.01830753, -0.01433732, -0.0